name: build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [~1.22, ^1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Build examples
        run: go build -v ./...
        working-directory: ./examples
